const starterProducts=[{name:"Ring Video Doorbell",category:"Smart Home",link:"https://amzn.to/4fm7SIV",desc:"Smart doorbell option for home security and package monitoring.",icon:"🔔",badge:"Smart Home"},{name:"Featured Amazon Pick",category:"Deals",link:"https://amzn.to/4f4t70P",desc:"Affiliate product ready for your featured deals section.",icon:"🛒",badge:"Featured"},{name:"Amazon Product Pick",category:"Deals",link:"https://amzn.to/4eKv6s8",desc:"Affiliate product ready to be organized into a category.",icon:"⭐",badge:"New"}];
function getProducts(){const saved=localStorage.getItem("csdf_products");if(saved){return JSON.parse(saved)}localStorage.setItem("csdf_products",JSON.stringify(starterProducts));return starterProducts}
function saveProducts(products){localStorage.setItem("csdf_products",JSON.stringify(products))}
function renderProducts(){const holder=document.getElementById("productGrid");if(!holder)return;const products=getProducts();const q=(document.getElementById("siteSearch")?.value||"").toLowerCase();holder.innerHTML=products.filter(p=>(p.name+p.category+p.desc).toLowerCase().includes(q)).map(p=>`<div class="product"><span class="badge">${p.badge||p.category}</span><div class="product-img">${p.icon||"🛒"}</div><h3>${p.name}</h3><p>${p.desc}</p><div class="stars">★★★★★</div><div class="price">View current price on Amazon</div><a class="shop" href="${p.link}" target="_blank" rel="nofollow sponsored noopener">View on Amazon</a></div>`).join("")}
function runStoreSearch(){const input=document.getElementById("siteSearch");if(!input)return;const q=input.value.trim();if(!q)return;if(!location.pathname.endsWith("/products.html")&&!location.pathname.endsWith("products.html")){location.href="products.html?q="+encodeURIComponent(q);return}filterStaticProducts(q)}
function filterStaticProducts(q){const term=(q||"").trim().toLowerCase();const section=document.getElementById("featured-products");if(!section)return;const cards=[...section.querySelectorAll(".product")];let shown=0;cards.forEach(card=>{const match=!term||card.textContent.toLowerCase().includes(term);card.style.display=match?"":"none";if(match)shown++});let msg=document.getElementById("searchStatus");if(!msg){msg=document.createElement("p");msg.id="searchStatus";section.querySelector(".grid")?.before(msg)}msg.textContent=term?(shown?`${shown} product result${shown===1?"":"s"} for “${q}”.`:`No featured products matched “${q}”. Try Electronics, AirTag, Air Fryer, Smart Home, or Deals.`):"";if(term)section.scrollIntoView({behavior:"smooth",block:"start"})}
function renderAdminTable(){const body=document.getElementById("adminRows");if(!body)return;const products=getProducts();body.innerHTML=products.map((p,i)=>`<tr><td>${p.name}</td><td>${p.category}</td><td><a href="${p.link}" target="_blank">Open</a></td><td><button onclick="deleteProduct(${i})">Delete</button></td></tr>`).join("")}
function deleteProduct(i){const products=getProducts();products.splice(i,1);saveProducts(products);renderAdminTable()}
function addProduct(e){e.preventDefault();const product={name:document.getElementById("name").value,category:document.getElementById("category").value,link:document.getElementById("link").value,desc:document.getElementById("desc").value,icon:document.getElementById("icon").value||"🛒",badge:document.getElementById("category").value};const products=getProducts();products.push(product);saveProducts(products);e.target.reset();renderAdminTable();alert("Product saved in this browser. Export the list before clearing browser data.")}
function exportProducts(){const data=JSON.stringify(getProducts(),null,2);const blob=new Blob([data],{type:"application/json"});const url=URL.createObjectURL(blob);const a=document.createElement("a");a.href=url;a.download="products.json";a.click()}
document.addEventListener("DOMContentLoaded",()=>{renderProducts();renderAdminTable();const search=document.getElementById("siteSearch");const button=document.getElementById("siteSearchButton");search?.addEventListener("keydown",e=>{if(e.key==="Enter")runStoreSearch()});button?.addEventListener("click",runStoreSearch);const params=new URLSearchParams(location.search);const q=params.get("q");if(q&&search){search.value=q;filterStaticProducts(q)}document.getElementById("productForm")?.addEventListener("submit",addProduct);document.getElementById("exportBtn")?.addEventListener("click",exportProducts);});